#! /bin/csh -f
set INCLUDE = /www/C_Interfaces_and_Implementations/include
set CSLIB = /www/C_Interfaces_and_Implementations/libcii.a
set LIBRARIES = ($CSLIB -lX11 -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
